controller_list:
  - name: arm_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - elbow_pitch
      - shoulder_base
      - shoulder_pitch
      - shoulder_yaw
      - wrist_pitch
      - wrist_roll
      - wrist_yaw
  - name: claw_controller
    type: FollowJointTrajectory
    action_ns: gripper_action
    default: true
    joints:
      - claw_left
      - claw_right
