controller_list:
  - name: arm_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - elbow_pitch
      - shoulder_base
      - shoulder_pitch
      - shoulder_yaw
      - wrist_pitch
      - wrist_roll
      - wrist_yaw
